set shell := ["bash", "-euo", "pipefail", "-c"]

default: ci

setup:
    python -m pip install -e ".[dev]"

build:
    python -m compileall -q spikeforge_targets

test:
    pytest

lint:
    ruff check .

format:
    ruff format .

typecheck:
    @echo "No repository typecheck command is configured."

run:
    spikeforge-targets --help

clean:
    @echo "No tracked build output is generated by the source test path."

docs:
    @echo "See README.md and the package docstrings."

ci: build lint test
